server:
  port: 8080

spring:
  application:
    name: seata-xa-demo
  datasource:
    url: jdbc:mysql://localhost:3306/seata-xa-1?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: account-db-pool
    order:
      url: jdbc:mysql://localhost:3306/seata-xa-2?useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: account-db-pool
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

seata:
  tx-service-group: my_test_tx_group
  service:
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
  config:
    type: file
  registry:
    type: file
  data-source-proxy-mode: XA